### ISSUE TITLE
Sender e-mail need to change 

### ISSUE THREAD

**Issue by ZgrK** [rajurayhan/laravel-ews-mail-server#1]
https://github.com/rajurayhan/laravel-ews-mail-server/blob/f2776f62304c27f97d5de8591feca9b37944d8bb/src/ExchangeMailServer.php#L59

This line of code saying as hardcode I guess better to change with this 

config('ews-mail-server.username');

**Comment by ZgrK** [comment]
@rajurayhan I create pull request for this https://github.com/rajurayhan/laravel-ews-mail-server/pull/2 you can check it like that working in our project

**Comment by rajurayhan** [comment]
Merged the patch @ZgrK Thanks!
